# Introduction to NumPy Arrays
NumPy (short for Numerical Python) is a linear algebra library that provides data structures for rsepresenting a rich veriety of  arrays,and methods and functions for operationg on such arrays.

The focus of this note will be on the NumPy ndarray class (used to instantiate a multidimensional array object).

The NumPy ndarray is a fast and flexible multidimensional container for large and homogenous data sets. Homogenous in the sense  that all elements will be of the same data type. Besides the data stored in the array, the data structure also contains  important metadata about the array which can be accessed with attributes such as (shape,size,dtype, etc...)

This Note will cover:
+ [Attributes](#Attributes)
+ [Basic data types](#Basic_data_types)
+ [Creating ndarrays](#Creating_ndarrays)

In [1]:
# import numpy module as np
import numpy as np

*The NumPy module was imported as np, this is done by convention and for convenience, hence we can access the methods and attributes of NumPy using the np name space. The fundanemtal way of creating an array object is by using the array function, and passing in a list.* 

In [17]:
list1 = [1,2,3,4,5,6]
list2 = [[1,2,3],[4,5,6],[7,8,9]]

arr_1d = np.array(list1, dtype = np.float32)
arr_2d = np.array(list2, dtype = np.int32)

In [18]:
# One dimensional array
arr_1d

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [19]:
#Two dimensional array created by passing a list of list
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
type(arr_1d)

numpy.ndarray

**NB** *To quickly know the dimension of an array, count the number of opening or closing brackets, a one dimension array has just one opening or closing bracket, while a two dimension has two.*

<a id='Attributes'></a>

# Attributes
As stated earlier, the array object has some metadata about the array that can be accessed as attributes:  
**np.ndarray** *is loosely used to refere to a NumPy array object*

Attribute | Function | Description
:- | :- | :-
shape |np.ndarray.shape | A tuple that contains the number of elements for each dimension (axis) of the array
size |np.ndarray.size | The total number of elements in the array
ndim |np.ndarray.ndim | Number of dimensions (axis)
nbytes| np.ndarray.nbytes | Number of bytes used to store the data
dtype |np.ndarray.dtype | The datatype of the elements in the array
itemsize |np.ndarray.itemsize| The size in bytes of each array element

In [5]:
# Shape of the array
arr_2d.shape

(3, 3)

In [6]:
# Size of the array
arr_2d.size

9

In [7]:
# Number of dimension
arr_2d.ndim

2

In [8]:
# Number of bytes of array
arr_2d.nbytes

36

In [9]:
# Type of data stored in array
arr_2d.dtype

dtype('int32')

In [10]:
# Size of each item in bytes
arr_2d.itemsize

4

<a id='Basic_data_types'></a> 

# Basic Data types
NumPy arrays contain homogenous data with fixed data-types. As seen in the attribute section where we saw the dtype attribute, there are various data-types and we can choose a data-type to use based on purpose.

The required data-type can be specified when creating an array by passing in the data-type as a argument to the dtype parameter, Just as we did while creating arr_1d and arr_2d

below are the basic data types:

dtype | Variant | Description
:-|:-:|-:
**int** | int8, int16, int32, int64 | Integers
**unit** |unit8, unit16,unit32, unit64 |Unsigned(non negative) integers 
**bool** | bool | Boolean (True or False)
**float** | float16, float32, float64, float128 | Floating point numbers
**complex** | complex64, complex128, complex256 | Complex- valued floating point Numbers

In [21]:
# Initializing a data type
np.int8

numpy.int8

In [22]:
np.nan

nan

<a id='Creating_ndarrays'></a>

# Creating ndarray
There are various ways to create a NumPy array depending on the properties and application. Previously we created an array by using  the np.array function and passing a list to it, the limitation of this method is that its mainly for small arrays. There are situations where we need to create arrays that follow a given rule such as: arrays filled with constant values, increasing integers, uniformly spaced numbers, random numbers or even read data stored in a file. NumPy presents diffeerent ways to handle these requirements. The following subsections explore the various array creation methods 

#### Arrays Filled with Constant Values
Function | Description 
:-|:-
np.zeros(shape,dtype) | Create an array with the specidied dimension(shape) and data type filled with zeros
np.ones(shape,dtype) | Create an array with the specidied dimension(shape) and data type filled with ones
np.full(shape, fill_value, dtype=None,) | Return a new array of given shape and type, filled with `fill_value`
np.empty(shape, dtype=float) | Return a new array of given shape and type, without initializing entries 

**NB** *When the shape is two dimnemsion the parameters should pe pass as a tuple (rows,colums). If its one dimension the length is an integer, its also optional to specify the data-type*

In [23]:
# Two dimension 4X5 array filled with zeros
np.zeros(shape=(4,5), dtype = np.int16)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

In [11]:
# One dimension array of lenght 9 filled with ones
np.ones(shape = 9, dtype = np.int16)

array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [12]:
# Two dimension 2X3 array filled with 9
np.full((2,3),9,np.int8)

array([[9, 9, 9],
       [9, 9, 9]], dtype=int8)

In [13]:
#  Two dimension 4X3 Array of uninitialized (arbitrary) data of the given shape
np.empty((4,3))

array([[6.11003386e-312, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.49172956e+180],
       [1.72425188e-047, 4.75731737e-038, 4.79492569e-037],
       [6.29103101e-066, 2.08928336e-076, 2.80366266e-032]])

#### Array Filled with incremental Sequences
Function | Description 
:-|:-
np.arange(start,stop,step) | Return evenly spaced values between the specified start, stop and increament values. the stop value is excluded     
np.linspace(start,stop,num) | Return evenly spaced values within the specified start, stop. suing the specified number of elements

In [14]:
# Array of evenly spaced values between 0 and 20, the end value is excluded
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# Array of 10 equally spaced samples between 0 and 20
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

#### Array filled with properties of other other Arrays 
Function | Description 
:-|:-
np.ones_like() | Create array filled with ones but take properties like shape and data type from another existing array
np.zeros_like() | Create array filled with zeros but take properties like shape and data type from another existing array
np.empty_like() | Array of uninitialized (arbitrary) that take properties like shape and data type from another existing array

In [21]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype = np.int32)

In [22]:
arr, f"the shape is: {arr.shape} the type is {arr.dtype}"

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 'the shape is: (4, 3) the type is int32')

In [23]:
# Array filled with ones and properties from arr above
np.ones_like(arr)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [24]:
# Array filled with zeros and properties from arr above
np.zeros_like(arr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
# Array of uninitialized (arbitrary) that take properties from arr
np.empty_like(arr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### Matrix array
Function | Description 
:-|:-
np.identity(n, dtype) | Return the identity array, with ones on the diagonaland zeros elsewhere
np.eye(N, M, k) | Return a 2-D array with ones on the diagonal and zeros elsewhere (N= number of rows, M= Number of columns, K=diagonal offset)
np.diag(v, k=0) | Return an identity matrix array specified diagonals

In [26]:
# Identity 5x5  matrix array
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
# 4X4 two dimensional array with positive +1 offest from the diagonal
np.eye(4,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [28]:
# 4X4 array with custimized diagonal
np.diag([5,10,15,20])

array([[ 5,  0,  0,  0],
       [ 0, 10,  0,  0],
       [ 0,  0, 15,  0],
       [ 0,  0,  0, 20]])

#### Random Values
Function | Description 
:-|:-
np.random.randint(low, high, size) | Return the size of random integers from `low` (inclusive) to `high` (exclusive)
np.random.randn(n) | Return n sample (or samples) from the "standard normal" distribution.
np.random.rand(dn) | Return  Random valuesfrom a uniform distribution in a shape(dn)

In [29]:
# Array of 20 random over the interval of 10 and 50 
np.random.randint(10,50,20)

array([44, 27, 25, 44, 42, 34, 46, 11, 11, 12, 44, 46, 46, 32, 47, 32, 35,
       17, 27, 40])

In [30]:
# Array of 4x3 randomly generated numbers from standard normal distribution
np.random.randn(4,3)

array([[ 1.39158718, -0.17292201,  1.66576022],
       [ 0.54117253,  0.60456157,  0.91619894],
       [-1.75675483,  1.66019638, -0.26403986],
       [ 1.07384567,  0.33943164, -0.62917311]])

In [31]:
# Array of 2x3 randomly generated numbers from uniform distribution
np.random.rand(2,3)

array([[0.49041333, 0.53211559, 0.26141302],
       [0.77731015, 0.33850216, 0.68792268]])

#### From Files and Function
Function | Description 
:-|:-
np.fromfile(file, dtype=float) | Construct an array from data in a text or binary file
np.loadtxt(fname,delimiter) | Load data from a text file
np.genfromtxt(fname,delimiter) | Load data from a text file, with missing values handled as specified.
np.fromfunction(function, shape) | Construct an array by executing a function over each coordinat

In [32]:
# Array created from a function where i controls the rows and j controls the columns
np.fromfunction(lambda i,j: (i*2,j*2),(4,5))

(array([[0., 0., 0., 0., 0.],
        [2., 2., 2., 2., 2.],
        [4., 4., 4., 4., 4.],
        [6., 6., 6., 6., 6.]]),
 array([[0., 2., 4., 6., 8.],
        [0., 2., 4., 6., 8.],
        [0., 2., 4., 6., 8.],
        [0., 2., 4., 6., 8.]]))